/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_sooorajjj_samplejniexample_SquareLib */

#ifndef _Included_com_example_sooorajjj_samplejniexample_SquareLib
#define _Included_com_example_sooorajjj_samplejniexample_SquareLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_sooorajjj_samplejniexample_SquareLib
 * Method:    squareN
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_sooorajjj_samplejniexample_SquareLib_squareN
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
