/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_example_sooorajjj_samplejniexample_SquareLib.h"

JNIEXPORT jint JNICALL Java_com_example_sooorajjj_samplejniexample_SquareLib_squareN
  (JNIEnv *env, jclass clazz, jint n){
        return (n*n);
  }


